### ISSUE TITLE
Demo原生，无法用AnotherActor继承Blueprint

### ISSUE THREAD

**Issue by huangwc94** [chexiongsheng/puerts_unreal_demo#10]
很奇怪，QuickTest里面可以成功用JS继承blueprint，但是如果用JS Blueprint来继承则返回错误
~~~
Puerts: Warning: (0x000002F2B58F7FD0) JS Execution Exception: E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\puerts\uelazyload.js:23: Error: TestBlueprint_C is blueprint type, load it using puerts.blueprint.
Error: TestBlueprint_C is blueprint type, load it using puerts.blueprint.
    at Object.get (E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\puerts\uelazyload.js:23:38)
    at getUClassOfType (E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1042:30)
    at E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1014:54
    at visitNodes (E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\PuertsEditor\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\PuertsEditor\node_modules\typescript\lib\typescript.js:16742:24)
    at onSourceFileAddOrChange (E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1004:28)
    at E:\Unreal\xiuxian\client\puerts_unreal_demo\Content\JavaScript\PuertsEditor\CodeAnalyze.js:941:29
~~~

AnotherActor被改为如下：
~~~typescript
import * as UE from "ue";
import { blueprint } from "puerts";

const TestBlueprint = blueprint<typeof UE.TestBlueprint_C>(
  "/Game/StarterContent/TestBlueprint.TestBlueprint_C"
);

class AnotherActor extends TestBlueprint {
  //注意，继承UE类的js类，构造函数必须大写开头
  Constructor() {
    console.warn("AnotherActor.Constructor");
  }

  //override 1
  ReceiveBeginPlay(): void {
    console.warn("AnotherActor.ReceiveBeginPlay");
  }
}

export default AnotherActor;

~~~

**Comment by huangwc94** [comment]
Unreal 4.24

**Comment by huangwc94** [comment]
貌似与https://github.com/Tencent/puerts/commit/b21f4647981ec1c0632752eb5ea620e6b45eefaf有关

**Comment by huangwc94** [comment]
给自己找到一个wordaround
让ts动态生成此class，而不是一开始就编译好。

~~~typescript
// AnotherActor.ts
export class AnotherActor extends TestBlueprint {
  //注意，继承UE类的js类，构造函数必须大写开头
  Constructor() {
    console.warn("AnotherActor.Constructor");
  }

  //override 1
  ReceiveBeginPlay(): void {
    console.warn("AnotherActor.ReceiveBeginPlay");
  }
}

// Other Class. eg: GameInstance
import { AnotherActor } from "./AnotherActor";
import { makeUClass } from "puerts";

const cls = makeUClass(AnotherActor);

class TsTestGameInstance extends UE.GameInstance {
  ReceiveInit(): void {
    console.warn("TsTestGameInstance.ReceiveInit");
    const atr = this.GetWorld().SpawnActor(
      cls,
      null,
      UE.ESpawnActorCollisionHandlingMethod.AlwaysSpawn,
      null,
      null
    ) as AnotherActor;
    atr.AnotherFunction();
    atr.Foo(false, 1, 2);
  }

  ReceiveShutdown(): void {
    console.warn("TsTestGameInstance.ReceiveShutdown");
  }
}
~~~
不知道这样做有没有性能损失，而且如果多次makeUClass，会不会有问题

**Comment by chexiongsheng** [comment]
目前禁用了通过UE.XXX去访问一个蓝图类，这种方式并不安全：这个蓝图没加载的话，会失败，加载了后续也可能会被gc。所以蓝图现在统一只能通过blueprint加载。
blueprint加载需要知道路径，而蓝图生成模块并不能从语法分析中获取该路径，通过UE.XXX去加载就报错了。
结论：目前不支持ts去继承蓝图。

**Comment by chexiongsheng** [comment]
ts继承蓝图是在什么场景下用呢？我看看支持的必要性

**Comment by huangwc94** [comment]
并不是我想ts继承蓝图，而是如果蓝图继承ts的话，会有https://github.com/Tencent/puerts/issues/173问题。每次更改ts都导致蓝图的名字改变。我测试了在ue4.24下面也有这个问题。
所以目前ts继承蓝图在我这里目前是唯一解。看如果能解决蓝图继承ts不会导致每次蓝图都改变，那我就不用ts继承蓝图了

**Comment by chexiongsheng** [comment]
“更改ts都导致蓝图的名字改变”，能搞个简单的例子给我么？

**Comment by huangwc94** [comment]
~~~typescript
import * as UE from "ue";

export class TestTSActor extends UE.Actor {
  MyCustomizedFunction(): void {
    console.log("Hello world2");
  }
  AnotherFunction():void {
    console.log("Another Function");
  }
}

export default TestTSActor;
~~~

创建新蓝图，并覆写 MyCustomizedFunction。保存蓝图。之后随意更改任意ts的内容触发重新编译，蓝图里面的覆写就消失了，变成
![image](https://user-images.githubusercontent.com/8810189/111271471-75343b00-85ee-11eb-8036-5029b8f2e49f.png)


另外，在蓝图中尝试调用`AnotherFunction()`。保存蓝图，随意更改任意ts内容触发重新编译，蓝图里面就显示error，并且无法直接PIE
![image](https://user-images.githubusercontent.com/8810189/111271803-ef64bf80-85ee-11eb-9d65-09ea6cd61f54.png)

**Comment by weyenrooney** [comment]
我提一个建议,unreal的  unlua与蓝图的配合就很完美,声明变量是在蓝图里面声明,lua可以直接访问调用.蓝图里面声明的函数,lua里面实现一份就覆盖,没有实现就调用蓝图原本的.这样有很多琐碎的赋值操作都能在编辑器里面完成,非常高效.
而现在puerts 只要ts里面有改动编译,在蓝图里面增加的变量就消失了,跟lua对比非常不方便

**Comment by chexiongsheng** [comment]
> 我提一个建议,unreal的 unlua与蓝图的配合就很完美,声明变量是在蓝图里面声明,lua可以直接访问调用.蓝图里面声明的函数,lua里面实现一份就覆盖,没有实现就调用蓝图原本的.这样有很多琐碎的赋值操作都能在编辑器里面完成,非常高效. 而现在puerts 只要ts里面有改动编译,在蓝图里面增加的变量就消失了,跟lua对比非常不方便

看下文档啊，你不加ts构造函数，就可以在蓝图那填值。
你加了ts构造函数，表示你希望在ts那赋值。
二选一

**Comment by weyenrooney** [comment]
可是实际应用中有问题,ts中没有constructor 在一个蓝图中增加了一个array类型的变量,在ts中声明该变量,第一次编译蓝图的时候该变量的访问都是正常的,当在ts有代码变动,再编译一次,蓝图中的array 变量就消失了

**Comment by chexiongsheng** [comment]
> 可是实际应用中有问题,ts中没有constructor 在一个蓝图中增加了一个array类型的变量,在ts中声明该变量,第一次编译蓝图的时候该变量的访问都是正常的,当在ts有代码变动,再编译一次,蓝图中的array 变量就消失了

可以改值。添加成员要在ts添加，那个蓝图你理解为ts“类”生成一个代理。

**Comment by weyenrooney** [comment]
这个地方有bug,
class TS_Actor extends UE.Actor {
    @edit_on_instance()
    ABill: boolean=false;
    @edit_on_instance()
   BTest: boolean;
    @edit_on_instance()
    GridList:UE.TArray<UE.st_grid>;

    // Constructor() {
    //     console.log("TS_Actor constructor 22");
    // }
    test1():void {
        console.log("ts test3 ",this.BTest,this.GridList.Num());

    }

}

class TS_gridActor extends UE.Actor {

    @edit_on_instance()
    cnt:number=0;
    @edit_on_instance()
    GridList:UE.TArray<UE.st_grid>;

    // Constructor() {
    //     console.log("TS_Actor constructor 22");
    // }

    //ContainerKVType<SupportedContainerKVType>
    //GridList:TArray<ContainerKVType<UE.st_grid>>;

    test1():void {


        console.log("TS_gridActor test9 num is ",this.GridList.Num());

    }

}

export default TS_gridActor;
2个测试类,都声明了GridList:UE.TArray<UE.st_grid>; st_grid是自定义的蓝图结构体
其中一个类在蓝图中能正确显示  GridList 变量,一个不能正确显示,郁闷

**Comment by chexiongsheng** [comment]
需要生成到蓝图的字段，不支持纯蓝图类型，只支持C++和ts
