### ISSUE TITLE
在开启PuertsSetting.Enable开关后，DebugEditor启动报错，且退出时存在崩溃。

### ISSUE THREAD

**Issue by mysticfarer** [chexiongsheng/puerts_unreal_demo#17]
# 环境
分支：master
IDE：Visual Studio 2019
启动配置：Debug Editor / Win64 / puerts_unreal_demo

DefaultPuerts.ini：
```ini
[/Script/Puerts.PuertsSetting]
Enable=True
```

# 问题描述
打开 `Puerts Module Enable` 开关，以 `Debug Editor` 启动后，日志中出现以下错误：
```log
[2021.05.31-02.25.15:109][  0]Puerts: Error: (0x000002814CF2DC10) load module [TsTestGameInstance] exception C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:89: Error: can not find [react-reconciler]

Error: can not find [react-reconciler]
    at require (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:89:30)
    at C:\puerts_unreal_demo\Content\JavaScript\react-umg\react-umg.js:3:20
    at executeModule (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:66:9)
    at require (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:118:17)
    at C:\puerts_unreal_demo\Content\JavaScript\react-umg\index.js:3:18
    at executeModule (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:66:9)
    at require (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:118:17)
    at C:\puerts_unreal_demo\Content\JavaScript\TsTestGameInstance.js:4:21
    at executeModule (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:66:9)
    at require (C:\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:118:17)
```

且退出调试时，在`FJsEnvImpl::~FJsEnvImpl()`函数释放 `DelegateMap` 处存在崩溃：
```
0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

**Comment by chexiongsheng** [comment]
can not find [react-reconciler]
安装依赖的模块就可以解决，项目目录执行：
npm install . 

崩溃我看下，你的UE是什么版本？

**Comment by mysticfarer** [comment]
> can not find [react-reconciler]
> 安装依赖的模块就可以解决，项目目录执行：
> npm install .
> 
> 崩溃我看下，你的UE是什么版本？

UE版本是4.26，只有Debug Editor会在退出时崩溃；Development Editor没有触发。

**Comment by mysticfarer** [comment]
### 补充1
在项目目录下执行过`npm install .`了，仍然会有上述 `can not find [react-reconciler]` 的错误；
npm及相关package的版本信息如下：

```bash
$ npm --version
6.14.13

$ npm list -g
C:\Users\U\AppData\Roaming\npm
`-- typescript@4.2.4

$ npm list
tsproj@1.0.0 C:\puerts_unreal_demo
+-- @types/mocha@7.0.2
+-- @types/react@15.6.28
`-- @types/react-reconciler@0.18.0
  `-- @types/react@15.6.28 deduped
```

### 补充2
退出时崩溃的具体位置：`JsEnvImpl.cpp, line 383`

**Comment by chexiongsheng** [comment]
另外，在Context/JavaScript下也要安装运行时依赖的模块
在那目录执行npm install .
