### ISSUE TITLE
UI无法启动

### ISSUE THREAD

**Issue by FishOrBear** [chexiongsheng/puerts_unreal_demo#2]
最开始的错误
```
TGameJS: Error: (0x0000019DD8484698) E:\Example\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:59: Error: can not find [react-reconciler]
            let moduleInfo = loadModule(moduleName, requiringDir);
```

然后我
```
npm i react
npm i react-reconciler
```

然后的错误是:
```
TGameJS: Error: (0x0000019DFA913560) E:\Example\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:61: Error: can not find [components.js]
            let moduleInfo = loadModule(moduleName, requiringDir);
                             ^
Error: can not find [components.js]
    at require (E:\Example\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:61:30)
    at E:\Example\puerts_unreal_demo\Content\JavaScript\react-umg\index.js:5:18
    at E:\Example\puerts_unreal_demo\Content\JavaScript\react-umg\index.js:12:3
    at E:\Example\puerts_unreal_demo\Content\JavaScript\react-umg\index.js:12:134
    at executeModule (E:\Example\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:45:16)
    at require (E:\Example\puerts_unreal_demo\Content\JavaScript\puerts\modular.js:79:21)
    at E:\Example\puerts_unreal_demo\Content\JavaScript\QuickStart.js:5:21
    at E:\Example\puerts_unreal_demo\Content\JavaScript\QuickStart.js:181:3
    at E:\Example\puerts_unreal_demo\Content\JavaScript\QuickStart.js:181:102
```

此时我`npm i components.js`
或者是创建`components.js`也是不行的,似乎得正确的提供这个文件

**Comment by chexiongsheng** [comment]
和内部的一些项目组交流，他们的UI都是美术搞的，蓝图拖拽式的比较合适美术。所以ReactUMG组件暂时去掉了，只是保留了些核心代码。
你有需要用到react么？

**Comment by FishOrBear** [comment]
我会写React，所以想看看ReactUMG效果怎么样

**Comment by chexiongsheng** [comment]
你更新下代码。
然后进入QuickStart.ts那打开下面代码注释
```csharp
ReactUMG.init(world);
UI.Load();
```
编译ts
在Content\JavaScript下执行
```bash
npm install .
```
然后运行demo

**Comment by FishOrBear** [comment]
OK 已经可以用了 非常好
